name: Publish GitHub Container Registry

on:
  push:
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io
  REPO_NAME: ${{ github.event.repository.name }}
  REPOSITORY: ghcr.io/${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    # env:
      # To use Turborepo Remote Caching, uncomment the next lines and follow the steps below.
      # See https://turbo.build/docs/guides/ci-vendors/github-actions#remote-caching
      # TURBO_TEAM: ${{ vars.TURBO_TEAM }}
      # TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images:
            $REPO_NAME/web
            $REPO_NAME/server

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build images
        run: |
          echo ""

          echo "————————————————————————————————————————————————————————————"
          echo "  Repo name: $REPO_NAME"
          echo " Repository: $REPOSITORY/*"
          echo "        Tag: $TAG"
          echo "————————————————————————————————————————————————————————————"

          docker compose build

          docker image ls

      # - name: Push images
      #   run: docker compose push
